# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - run: echo -n -e "HELLO\n !\n World!" > text.txt

      - uses: pCYSl5EDgo/cat@master
        id: export
        with:
          path: ./exportConf.json

      - run: echo $TEXT
        env:
          TEXT: ${{ steps.export.outputs.text }}
      
      - name: Restore firebase.json file
        uses: kitek/decode-base64-into-file-action@1.0
        with:
          encoded-value: ${{ steps.export.outputs.text }}
          destination-file: out.json
      
      - name: Create File
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: "fileName.txt"
          FILE_DATA: "file content"
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply b64 to json
    
      #- name: base64-to-file
       # uses: timheuer/base64-to-file@v1
        #with:
         # fileName: 'exportConf.json'
          #encodedString: ${{ steps.hello.outputs.text }}

