# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: pCYSl5EDgo/cat@master
        id: exportNetworkZones
        with:
          path: ./networkZones.json
      
      - name: Decode NetworkZones
        uses: kitek/decode-base64-into-file-action@1.0
        with:
          encoded-value: ${{ steps.exportNetworkZones.outputs.text }}
          destination-file: networkZones.json
          
      - uses: pCYSl5EDgo/cat@master
        id: exportFeatures
        with:
          path: ./features.json
      
      - name: Decode Features
        uses: kitek/decode-base64-into-file-action@1.0
        with:
          encoded-value: ${{ steps.exportFeatures.outputs.text }}
          destination-file: features.json
          
      - uses: pCYSl5EDgo/cat@master
        id: exportMFAPolicies
        with:
          path: ./MFAPolicies.json
      
      - name: Decode MFAPolicies
        uses: kitek/decode-base64-into-file-action@1.0
        with:
          encoded-value: ${{ steps.exportMFAPolicies.outputs.text }}
          destination-file: MFAPolicies.json
          
      - uses: pCYSl5EDgo/cat@master
        id: exportGroups
        with:
          path: ./groups.json
      
      - name: Decode Groups
        uses: kitek/decode-base64-into-file-action@1.0
        with:
          encoded-value: ${{ steps.exportGroups.outputs.text }}
          destination-file: groups.json
          
      - uses: pCYSl5EDgo/cat@master
        id: exportGroupRules
        with:
          path: ./groupRules.json
      
      - name: Decode groupRules
        uses: kitek/decode-base64-into-file-action@1.0
        with:
          encoded-value: ${{ steps.exportGroupRules.outputs.text }}
          destination-file: groupRules.json
          
      - uses: pCYSl5EDgo/cat@master
        id: exportSignOnPolicies
        with:
          path: ./signOnPolicies.json
      
      - name: Decode signOnPolicies
        uses: kitek/decode-base64-into-file-action@1.0
        with:
          encoded-value: ${{ steps.exportSignOnPolicies.outputs.text }}
          destination-file: signOnPolicies.json
          
      - uses: pCYSl5EDgo/cat@master
        id: exportUserRolesAdmin
        with:
          path: ./userRolesAdmin.json
      
      - name: Decode userRolesAdmin
        uses: kitek/decode-base64-into-file-action@1.0
        with:
          encoded-value: ${{ steps.exportUserRolesAdmin.outputs.text }}
          destination-file: userRolesAdmin.json
          
      - uses: pCYSl5EDgo/cat@master
        id: exportGroupAdmin
        with:
          path: ./groupAdmin.json
      
      - name: Decode groupAdmin
        uses: kitek/decode-base64-into-file-action@1.0
        with:
          encoded-value: ${{ steps.exportGroupAdmin.outputs.text }}
          destination-file: groupAdmin.json
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply b64 to json
    
      #- name: base64-to-file
       # uses: timheuer/base64-to-file@v1
        #with:
         # fileName: 'exportConf.json'
          #encodedString: ${{ steps.hello.outputs.text }}

